Feature/measured values
UdSAES/dwd_data_access pull request #4
Opened 2020-08-17 09:07 UTC by IvannikovG

1). Openapi validation tests do not work yet, connection timeout
2). More tests can be written yet, at least for unit tests

2020-08-21 11:13 UTC, MoritzStueber requested changes
Detailed feedback on the internals; didn't have a look at the API tests yet (probably tomorrow). Looks promising so far!

2020-08-21 11:13 UTC, MoritzStueber commented on handlers/data_access.js
> +      vois = voi.split(',')
Only works if there are more than one quantities, crashes for exactly one

2020-08-21 11:13 UTC, MoritzStueber commented on handlers/data_access.js
>        startTimestamp = moment.utc().subtract(25, 'hours').valueOf()
Should default to start/end of today in timezone `Europe/Berlin` instead, see OAS

2020-08-21 11:13 UTC, MoritzStueber commented on handlers/data_access.js
> +    }
* `500` is the wrong HTTP status code, this is a `400 Bad Request`
* should return response of type `application/problem+json` as indicated in the OAS (compare line 246 in `index.js`, possibly just call that)

2020-08-21 11:13 UTC, MoritzStueber commented on handlers/data_access.js
> +        res.status(406).send('Not Acceptable')
Should return a problem detail object as suggested in RFC 7807, not plain text

* [ ] @MoritzStueber add to OAS
* [ ] @IvannikovG fix for all data handlers

2020-08-21 11:13 UTC, MoritzStueber commented on handlers/data_access.js
> +    // timeseriesDataArray = [[{str:int, str: null}, {...} <-tmstmp]<-voi,[{...}, {...}]<-voi]
Usually better to use comments to explain what is happening (possibly why) using natural language, not implementation details (also I don't get the notation in the second line). Example: `// Read all data for period, but only keep quantities requested by user` above the block

2020-08-21 11:13 UTC, MoritzStueber commented on handlers/data_access.js
> +// http://localhost:5000/weather-stations/10505/measured-values?quantities=t_2m&from=1597140000000&to=1597226400000
I guess you're copy-pasting this for testing interactively, but if we follow the pattern of the comments above the other handlers, this should be `GET /weather-stations/:stationId/measured-values?quantities=...&from=...&to=...`

2020-08-21 11:13 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +const _ = require('lodash')
File header missing: license information, statement `use strict` (see other files)

2020-08-21 11:13 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +function ensureVoiConfigsCorrectness (voiConfigs) {
Better name `checkValidityOfQuantityIds (voiConfigs) {}`? For me, 'ensure' implies that something broken is corrected and this is not what this function does. Also, `voiExists` instead of `trueVoisArray` might be more readable

2020-08-21 11:13 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +function getTimeSeriesData (voiConfigs, timeseriesDataCollection) {
Better name `dropTimeseriesDataNotOfInterest (..) {}`? Didn't know what the function was about with the old name, too generic I think

2020-08-21 11:13 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +function formatTimeseriesDataArray (timeseriesDataArray) {
* Better name `useSIunitsAndDropNaN () {}`?
* Please re-add the comments that existed, no reason to get rid of them!! See https://github.com/UdSAES/dwd_data_access/pull/4/files#diff-f6f98c8d039ad2cbafd38480ce2f132eL302-L323

2020-08-21 11:13 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +  for (let i = 0; i < voiConfigs.length; i += 1) {
Iteration based on numerical index assumes that `voiConfigs` and `timeseriesDataArray` have the same length and that their members are in the same order, can you guarantee that?

2020-08-21 11:13 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +  // returns from each array in timeseriesDataArray first element.
Comment doesn't match code

2020-08-21 11:13 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +function getLastElementsFromTimeseries (timeseriesDataArray) {
Better name `getAllButFirstElementsFromTimeseries (..) {}`?

2020-08-21 11:13 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +}
Cool, recursion! :sunglasses: Hard to understand at first sight, though. Also, why was this necessary, what's the advantage over a simple `_.forEach()` or similar? Please add comments that explain&increase readability!

Also, if it's not really necessary, this adds complexity and thus should probably be implemented as simple as possible. Even if the resulting code is not that cool... Don't know though.

2020-08-21 11:13 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +  return timeseriesDataArray
Unit conversion is missing! See https://github.com/UdSAES/dwd_data_access/pull/4/files#diff-f6f98c8d039ad2cbafd38480ce2f132eL326-L331

Here is probably a good place to implement this because it should happen before/outside the rendering functions.

2020-08-21 11:13 UTC, MoritzStueber commented on test/test_measured_values_utils.js
> +  const VOIS_DATA_ACCESS_CONFIGS_PATH = './config/vois_data_access.json'
Should probably go into a `before` or `beforeEach`-section to avoid code duplication and speed up execution

2020-08-21 11:13 UTC, MoritzStueber commented on test/test_measured_values_utils.js
> +      // Read expected result from .json-file
Comments no longer match code (throughout entire file) -- please update or remove; since the structure is always the same (expect, actual, assert) we can probably remove the comments

2020-08-23 10:08 UTC, IvannikovG commented on handlers/data_access.js
> +    }
Was not possible to call failValidation from index.js, produced errors.

Replaced with:
res.set('Content-Type', 'application/problem+json')
      res.status(400).json({
        title: 'Schema validation Failed',
        status: 400,
        detail: 'Received request for unconfigured voi',
      })

2020-08-23 10:44 UTC, IvannikovG commented on handlers/data_access.js
> +        res.status(406).send('Not Acceptable')
Introduced a function in responce_utils: problemDetail that accepts res and config. Res is responce object and config is an object containing {title: ..., status: ...,  detail: ..} According to RFC 7807.

2020-08-23 10:44 UTC, IvannikovG commented on handlers/data_access.js
> +    // timeseriesDataArray = [[{str:int, str: null}, {...} <-tmstmp]<-voi,[{...}, {...}]<-voi]
removed redundant comments

2020-08-23 10:50 UTC, IvannikovG commented on handlers/data_access.js
> +// http://localhost:5000/weather-stations/10505/measured-values?quantities=t_2m&from=1597140000000&to=1597226400000
True. Fixed

2020-08-23 10:52 UTC, IvannikovG commented on lib/measured_values_utils.js
> +const _ = require('lodash')
Fixed

2020-08-23 10:57 UTC, IvannikovG commented on lib/measured_values_utils.js
> +function ensureVoiConfigsCorrectness (voiConfigs) {
Fixed

2020-08-23 11:07 UTC, IvannikovG commented on lib/measured_values_utils.js
> +function getTimeSeriesData (voiConfigs, timeseriesDataCollection) {
Fixed

2020-08-23 11:20 UTC, IvannikovG commented on lib/measured_values_utils.js
> +function formatTimeseriesDataArray (timeseriesDataArray) {
Renamed and returned comments

2020-08-23 11:41 UTC, IvannikovG commented on lib/measured_values_utils.js
> +  // returns from each array in timeseriesDataArray first element.
Renamed this function to getHeadElementsFromTimeseries

2020-08-23 11:44 UTC, IvannikovG commented on lib/measured_values_utils.js
> +function getLastElementsFromTimeseries (timeseriesDataArray) {
Renamed this function to getHeadElementsFromTimeSeries

2020-08-23 12:04 UTC, IvannikovG commented on lib/measured_values_utils.js
> +}
I would like to ask you to allow me to keep it. For each is not possible, because:
I do not exactly iterate through timeseries for each voi, but also kind of inside each voi too.
E.g. timeseries would be smth like:

[[voi1_timeseries_el1, voi1_timeseries_el2],
 [voi2_timeseries_el1, voi2_timeseries_el2],
 [voi3_timeseries_el1, voi3_timeseries_el2]]

And i iterate by columns kind of, getting [[voi1_timeseries_el1, voi2_timeseries_el1, ... voiN...]]

So in my opinion this is a good usecase for such recursion. We can refactor later on but for now i assume adding comments will be enough? Because it does what intended..

2020-08-23 12:18 UTC, IvannikovG commented on handlers/data_access.js
> +      vois = voi.split(',')
Could not reproduce

2020-08-23 13:43 UTC, IvannikovG commented on test/test_measured_values_utils.js
> +  const VOIS_DATA_ACCESS_CONFIGS_PATH = './config/vois_data_access.json'
decided to keep same and rework in case of need when more tests are added to test/test_measured_values_utils.js.

2020-08-23 13:44 UTC, IvannikovG commented on test/test_measured_values_utils.js
> +      // Read expected result from .json-file
Fixed

2020-08-23 14:32 UTC, IvannikovG commented on handlers/data_access.js
> +      vois = voi.split(',')
Tested with 

http://localhost:5000/weather-stations/10505/measured-values?quantities=t_2m,aswdir_s,pmsl,t_2m&from=1597140000000&to=1597150000000

http://localhost:5000/weather-stations/10505/measured-values?quantities=t_2m&from=1597140000000&to=1597150000000

2020-08-23 14:56 UTC, IvannikovG commented on lib/measured_values_utils.js
> +  return timeseriesDataArray
Implemented in a separate function: convertUnits in utils

2020-08-23 15:57 UTC, MoritzStueber commented on handlers/data_access.js
> +      vois = voi.split(',')
Couldn't reproduce either :confused: ... Never mind

2020-08-23 16:04 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +}
All good, was just surprised and didn't really try to understand why it was necessary. Let's keep it :slightly_smiling_face:

2020-09-22 07:09 UTC, merged