Feature/mosmix forecasts
UdSAES/dwd_data_access pull request #5
Opened 2020-11-09 21:44 UTC by IvannikovG

Might cause a bit trouble with measured values, because this feature reuses a lot of functionality from there. Tests are very basic too

2020-11-21 17:02 UTC, MoritzStueber requested changes
Hi, I reviewed the entire pull request except `test/test_forecast_openapi_validation.js`.

Overall, I'm happy that you managed to pull this off -- it's been quite a task and I know from experience that understanding all the existing code is hard.

However, you introduced quite a bit of duplicated code throughout the files and the source files became quite hard to navigate. Therefore, I will restructure the code and reorganize files in order to hopefully increase ease of navigation.

Please review the comments on specific sections of code to get some feedback on your coding, but wait for my pull request before implementing any of the requested changes. I will start restructuring now, and aim to complete it by tomorrow (sunday) evening.

2020-11-21 17:02 UTC, MoritzStueber commented on handlers/data_access.js
> +const now = moment()
Careful, this code only gets executed when the module is first loaded, which could be months before a request arrives! Your attempt to reduce code duplication -- although honourable -- backfired :fire: :arrow_right: move back to request handlers

2020-11-21 17:02 UTC, MoritzStueber commented on handlers/data_access.js
> +      : parseInt(defaultEndTimestamp)
Ternary operators, cool :sunglasses:

2020-11-21 17:02 UTC, MoritzStueber commented on lib/csv.js
> +// dwd-csv-helper may be freely used and distributed under the ISC license
The other way round, please -- we want to use the short form suggested by SPDX instead of the verbose, end- and mindless copy-paste of license texts everywhere.

I'm guessing that changing the license from ISC to MIT is theoretically more complex than changing three characters, but I'm certain that these two licenses share the same intent and I'm therefore suggesting to use MIT throughout `dwd_data_access`

2020-11-21 17:02 UTC, MoritzStueber commented on lib/forecast_utils.js
> +function dropTimeseriesDataNotOfInteresWithParameter (
Typo in function name, please refactor

2020-11-21 17:02 UTC, MoritzStueber commented on lib/forecast_utils.js
> +})
use the one instantiated in `lib/logger.js` instead

2020-11-21 17:02 UTC, MoritzStueber commented on lib/forecast_utils.js
> +  }
Reaching this branch would indicate some mistake, thus the appropriate action would be to throw an error. Returning an empty dictionary is problematic because you overload this empty dictionary with the meaning "this is an error", which should instead be communicated by throwing properly.

2020-11-21 17:02 UTC, MoritzStueber commented on lib/forecast_utils.js
> +  }
Probably not that important because invalid model identifiers supplied by the user get caught before they ever reach this function, but still...

2020-11-21 17:02 UTC, MoritzStueber commented on handlers/data_access.js
> +        'received request for REPORT for unconfigured MODEL-RUN'
`detail` and log message should be the same; `REPORT` is wrong; `model-run` is not unconfigured, but faulty; capitalization unneccessary

:arrow_right: change to `User-supplied value for parameter 'model-run' does not match available choices for model ${model}`

2020-11-21 17:02 UTC, MoritzStueber commented on handlers/data_access.js
> +    log.debug('reading BEOB data from disk...')
wrong, `BEOB` refers to measured values only

2020-11-21 17:02 UTC, MoritzStueber commented on lib/csv.js
> +})
use the one in `lib/logger.js`

2020-11-21 17:02 UTC, MoritzStueber commented on lib/csv.js
> +function deriveCsvFilePath (csvBasePath, type, timestamp, stationId) {
:warning: I will stop reviewing this file in this PR since it is currently not used by any other code.

2020-11-21 17:02 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +
This probably breaks loading measurement data entirely... Commit more carefully and commit more often :wink:

2020-11-21 17:02 UTC, MoritzStueber commented on lib/forecast_utils.js
> +}
Programmers often name such test functions that return `true` or `false` `isSomething`, e.g. `isValidModelRun` :arrow_right: tests can then be read more naturally, e.g. ` if (!isValidModelRun())` reads "if not is valid model run" as compared to "if not check if valid model run" -- subtle difference, but I think it makes sense to rename

2020-11-21 17:02 UTC, MoritzStueber commented on lib/measured_values_utils.js
> +
Ok, I see -- doesn't break the code because the function is no longer called. Nonetheless, this means that you now have dead code lying around (not good).

I will take care of this while restructuring.

2020-11-21 17:02 UTC, MoritzStueber commented on handlers/data_access.js
> +        const localForecast = await config.jsonRenderer(
rename `localForecast` to `forecastRepresentation` because the latter is more precise -- also line 562, 566, 567

2020-11-21 17:02 UTC, MoritzStueber commented on handlers/data_access.js
> +    const vois = gu.getVoisNamesFromQuery(req.query)
move down one line so that empty line separates code block for handling invalid user input from loading config for VOIs in case the input was correct

2020-11-21 17:02 UTC, MoritzStueber commented on lib/forecast_utils.js
> +      .slice(0, -2) + modelRun
will break reading the measured values (case `REPORT`) because the assumption on which `.slice(0, -2)` operates no longer holds

2020-11-21 17:02 UTC, MoritzStueber commented on handlers/data_access.js
> +      ? parseInt(req.query.from)
`req.query.to` !!

2020-11-21 17:02 UTC, MoritzStueber commented on handlers/data_access.js
> +    // log.trace({ timeseriesDataArrayUnformatted })
if it doesn't serve a purpose, it should not have been included in commit/PR :wink:

2020-11-25 10:19 UTC, MoritzStueber commented
> Please review the comments on specific sections of code to get some feedback on your coding, but wait for my pull request before implementing any of the requested changes. I will start restructuring now, and aim to complete it by tomorrow (sunday) evening.

Done: PR #6

2020-11-25 10:19 UTC, MoritzStueber commented on handlers/data_access.js
> +      ? parseInt(req.query.from)
fixed that

2020-11-25 10:21 UTC, MoritzStueber commented on lib/forecast_utils.js
> +      .slice(0, -2) + modelRun
resolve when integrating `dwd-csv-helper` into code base; discuss with me first

2020-11-25 10:22 UTC, MoritzStueber commented on lib/forecast_utils.js
> +function dropTimeseriesDataNotOfInteresWithParameter (
Nevermind, function is gone

2020-12-06 13:20 UTC, IvannikovG commented on handlers/data_access.js
> +const now = moment()
Moved

2020-12-06 13:23 UTC, IvannikovG commented on handlers/data_access.js
> +    // log.trace({ timeseriesDataArrayUnformatted })
👍

2020-12-06 13:25 UTC, IvannikovG commented on lib/forecast_utils.js
> +  }
I think it will 100% catch incorrect model in the step when we analyse query string, so this is even optional step. My opinion - keep it like it is

2020-12-06 13:28 UTC, IvannikovG commented on handlers/data_access.js
> +        'received request for REPORT for unconfigured MODEL-RUN'
Makes sense

2020-12-06 13:31 UTC, IvannikovG commented on handlers/data_access.js
> +    log.debug('reading BEOB data from disk...')
renamed to 'reading timeseries data from disk...'

2020-12-06 13:32 UTC, IvannikovG commented on lib/csv.js
> +})
I think you have fixed it

2020-12-06 13:36 UTC, IvannikovG commented on lib/forecast_utils.js
> +})
forecast utils was separated in a way that id does not include logger anymore. just pure functions

2020-12-06 13:41 UTC, IvannikovG commented on lib/forecast_utils.js
> +}
Renamed

2020-12-06 13:42 UTC, IvannikovG commented on handlers/data_access.js
> +        const localForecast = await config.jsonRenderer(
Renamed

2021-01-10 11:50 UTC, merged